/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Michelle Alvarado
 */
public class MiniPC extends javax.swing.JFrame {
    public File selectedFile;
    /**
     * Creates new form MiniPC
     */
    public MiniPC() {
        initComponents();
    }
    
    @Override
    public Image getIconImage() {
       Image retValue = Toolkit.getDefaultToolkit().
             getImage(ClassLoader.getSystemResource("GUI/Images/pc_icon.png"));


       return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        headerContainer = new javax.swing.JPanel();
        OpenFolderButton = new javax.swing.JButton();
        registerTabbedPane = new javax.swing.JTabbedPane();
        registerContainer = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pcRegisterLabel = new java.awt.Label();
        acRegisterLabel = new java.awt.Label();
        irRegisterLabel = new java.awt.Label();
        axRegisterLabel = new java.awt.Label();
        bxRegisterLabel = new java.awt.Label();
        cxRegisterLabel = new java.awt.Label();
        dxRegisterLabel = new java.awt.Label();
        pcValueLabel = new java.awt.Label();
        acValueLabel = new java.awt.Label();
        irValueLabel = new java.awt.Label();
        axValueLabel = new java.awt.Label();
        bxValueLabel = new java.awt.Label();
        cxValueLabel = new java.awt.Label();
        dxValueLabel = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        codeTable = new javax.swing.JTable();
        nextButton = new javax.swing.JButton();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MiniPC");
        setIconImage(getIconImage());

        container.setBackground(new java.awt.Color(204, 204, 235));

        OpenFolderButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/folder-open-flat.png"))); // NOI18N
        OpenFolderButton.setActionCommand("openFile");
        OpenFolderButton.setBorder(null);
        OpenFolderButton.setBorderPainted(false);
        OpenFolderButton.setContentAreaFilled(false);
        OpenFolderButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        OpenFolderButton.setFocusPainted(false);
        OpenFolderButton.setFocusable(false);

        javax.swing.GroupLayout headerContainerLayout = new javax.swing.GroupLayout(headerContainer);
        headerContainer.setLayout(headerContainerLayout);
        headerContainerLayout.setHorizontalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerContainerLayout.createSequentialGroup()
                .addComponent(OpenFolderButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        headerContainerLayout.setVerticalGroup(
            headerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OpenFolderButton, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
        );

        registerTabbedPane.setFocusable(false);
        registerTabbedPane.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        registerTabbedPane.setRequestFocusEnabled(false);

        registerContainer.setBackground(new java.awt.Color(255, 255, 255));

        pcRegisterLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        pcRegisterLabel.setText("PC:");

        acRegisterLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        acRegisterLabel.setText("AC:");

        irRegisterLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        irRegisterLabel.setText("IR:");

        axRegisterLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        axRegisterLabel.setText("AX:");

        bxRegisterLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        bxRegisterLabel.setText("BX:");

        cxRegisterLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        cxRegisterLabel.setText("CX:");

        dxRegisterLabel.setFont(new java.awt.Font("Bahnschrift", 1, 14)); // NOI18N
        dxRegisterLabel.setText("DX:");

        pcValueLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        pcValueLabel.setText("0");

        acValueLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        acValueLabel.setText("0");

        irValueLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        irValueLabel.setText("-");

        axValueLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        axValueLabel.setText("0");

        bxValueLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        bxValueLabel.setText("0");

        cxValueLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        cxValueLabel.setText("0");

        dxValueLabel.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        dxValueLabel.setText("0");

        javax.swing.GroupLayout registerContainerLayout = new javax.swing.GroupLayout(registerContainer);
        registerContainer.setLayout(registerContainerLayout);
        registerContainerLayout.setHorizontalGroup(
            registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(registerContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pcRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(irRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(1, 1, 1)
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(irValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(acValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pcValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(axRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bxRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dxRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(axValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(304, Short.MAX_VALUE))
        );
        registerContainerLayout.setVerticalGroup(
            registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerContainerLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(registerContainerLayout.createSequentialGroup()
                        .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(registerContainerLayout.createSequentialGroup()
                                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pcRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pcValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(acValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(irRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(irValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(axRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(axValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(bxRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(cxRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(registerContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dxRegisterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pcRegisterLabel.getAccessibleContext().setAccessibleName("pcRegisterLabel");
        acRegisterLabel.getAccessibleContext().setAccessibleName("acRegisterLabel");
        irRegisterLabel.getAccessibleContext().setAccessibleName("irRegisterLabel");
        axRegisterLabel.getAccessibleContext().setAccessibleName("axRegisterLabel");
        bxRegisterLabel.getAccessibleContext().setAccessibleName("bxRegisterLabel");
        cxRegisterLabel.getAccessibleContext().setAccessibleName("cxRegisterLabel");
        dxRegisterLabel.getAccessibleContext().setAccessibleName("dxRegisterLabel");
        pcValueLabel.getAccessibleContext().setAccessibleName("pcValueLabel");
        acValueLabel.getAccessibleContext().setAccessibleName("acValueLabel");
        irValueLabel.getAccessibleContext().setAccessibleName("irValueLabel");
        axValueLabel.getAccessibleContext().setAccessibleName("axValueLabel");
        bxValueLabel.getAccessibleContext().setAccessibleName("bxValueLabel");
        cxValueLabel.getAccessibleContext().setAccessibleName("cxValueLabel");
        dxValueLabel.getAccessibleContext().setAccessibleName("dxValueLabel");

        registerTabbedPane.addTab("Registros", registerContainer);

        codeTable.setFont(new java.awt.Font("Bahnschrift", 0, 13)); // NOI18N
        codeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Posición memoria", "Código ASM", "Código Binario"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        codeTable.setRowHeight(26);
        jScrollPane1.setViewportView(codeTable);
        codeTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        codeTable.getColumnModel().getColumn(1).setPreferredWidth(130);
        codeTable.getColumnModel().getColumn(2).setPreferredWidth(130);

        nextButton.setBackground(new java.awt.Color(204, 204, 235));
        nextButton.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/next.png"))); // NOI18N
        nextButton.setText("Siguiente");
        nextButton.setActionCommand("next");
        nextButton.setBorder(null);
        nextButton.setBorderPainted(false);
        nextButton.setContentAreaFilled(false);
        nextButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nextButton.setEnabled(false);
        nextButton.setFocusPainted(false);
        nextButton.setFocusable(false);

        startButton.setBackground(new java.awt.Color(204, 204, 235));
        startButton.setFont(new java.awt.Font("Bahnschrift", 1, 16)); // NOI18N
        startButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/power.png"))); // NOI18N
        startButton.setText("Iniciar");
        startButton.setActionCommand("start");
        startButton.setBorder(null);
        startButton.setBorderPainted(false);
        startButton.setContentAreaFilled(false);
        startButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startButton.setFocusPainted(false);
        startButton.setFocusable(false);

        javax.swing.GroupLayout containerLayout = new javax.swing.GroupLayout(container);
        container.setLayout(containerLayout);
        containerLayout.setHorizontalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(containerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(registerTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(startButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nextButton)
                        .addGap(25, 25, 25))))
        );
        containerLayout.setVerticalGroup(
            containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerLayout.createSequentialGroup()
                .addComponent(headerContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(registerTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(containerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton)
                    .addComponent(startButton))
                .addGap(27, 27, 27))
        );

        headerContainer.getAccessibleContext().setAccessibleName("");
        registerTabbedPane.getAccessibleContext().setAccessibleName("registros");
        nextButton.getAccessibleContext().setAccessibleName("nextButton");
        startButton.getAccessibleContext().setAccessibleName("startButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton OpenFolderButton;
    public java.awt.Label acRegisterLabel;
    public java.awt.Label acValueLabel;
    public java.awt.Label axRegisterLabel;
    public java.awt.Label axValueLabel;
    public java.awt.Label bxRegisterLabel;
    public java.awt.Label bxValueLabel;
    public javax.swing.JTable codeTable;
    private javax.swing.JPanel container;
    public java.awt.Label cxRegisterLabel;
    public java.awt.Label cxValueLabel;
    public java.awt.Label dxRegisterLabel;
    public java.awt.Label dxValueLabel;
    private javax.swing.JPanel headerContainer;
    public java.awt.Label irRegisterLabel;
    public java.awt.Label irValueLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public javax.swing.JButton nextButton;
    public java.awt.Label pcRegisterLabel;
    public java.awt.Label pcValueLabel;
    private javax.swing.JPanel registerContainer;
    private javax.swing.JTabbedPane registerTabbedPane;
    public javax.swing.JButton startButton;
    // End of variables declaration//GEN-END:variables
}
